export class ReceiptPoints {
    /**
     * 
     * @param {*} id // UUID generated by processReceiptById in receipt_controller.js
     * @param {*} points // Number of points caluclated from receipt in receipt_controller.js
     */
    constructor(id, points) {
        this.id = id
        this.points = points
    }
}